name: Build/Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*" # Triggers on version tags like v0.0.2, v1.0.0, etc.
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Build package
        run: uv build

      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          UV_PUBLISH_USERNAME: ${{ secrets.PYPI_USERNAME }}
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: uv publish
